engines:
  pep8:
    enabled: true
  fixme:
    enabled: true
  pylint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      	  mass_threshold: 30
      - javascript
ratings:
  paths:
  - serviceform/**
  - "**.py"
exclude_paths:
 - "serviceform/serviceform/static/assets/"
 - "serviceform/serviceform/static/Font-Awesome/"
 - "serviceform/serviceform/static/select2/"
 - "tests/"
 - "**/migrations/"