engines:
  pep8:
    enabled: true
ratings:
  paths:
  - serviceform/**
  - "**.py"
exclude_paths:
 - "serviceform/serviceform/static/assets/"
 - "serviceform/serviceform/static/Font-Awesome/"
 - "serviceform/serviceform/static/select2/"
 - "tests/"
 - "**/migrations/"