sudo: required
language: python
python:
  - "3.7"

services:
  - docker

before_install:
 - sudo ln -s $(pwd) /code
 - sudo chmod a+rw .

install:
 - pip install --upgrade docker-compose
 - CURRENT_DIR=$(pwd) docker-compose -f docker-compose-travis.yml build
 - pip install coveralls codeclimate-test-reporter coverage==4.3.4

script:
 - CURRENT_DIR=$(pwd) docker-compose -f docker-compose-travis.yml run tests

after_success:
 - coveralls
 - codeclimate-test-reporter
