# Compose file to run all tests

version: "2"

services:
  redis:
    image: redis:3.2.8-alpine
  db:
     image: postgres:9.6.2
     environment:
      - POSTGRES_USER=serviceform
      - POSTGRES_DB=test_serviceform
      - POSTGRES_PASSWORD=django
  tests:
    build: .
    user: root
    image: serviceform
    command: tests
    links:
      - db
      - redis


