# Compose file to set up environment for tests in travis

version: "2"

services:
  redis:
    image: redis:3.2.8-alpine
  db:
    image: postgres:9.6.2
    environment:
     - POSTGRES_USER=serviceform
     - POSTGRES_DB=test_serviceform
     - POSTGRES_PASSWORD=django
  tests:
    build:
      context: .
      args:
        VERSION: tests
    image: serviceform
    user: root
    command: travis-tests ${CURRENT_DIR}
    volumes:
      - ${CURRENT_DIR}:${CURRENT_DIR}
    links:
      - db
      - redis