version: "2"

# Environment is similar to production

volumes:
  static:
  media:
  nginx-config:
  celery-beat-store:
  staging-db:
  staging-redis:

services:
  # Nginx web server is only for development environment. Disabled in production.

  staging-redis:
    env_file: env/staging.list
    image: redis:3.2.5-alpine
    volumes:
      - staging-redis:/data

  staging-db:
     image: postgres:9.6.1
     env_file: env/staging.list
     volumes:
      - staging-db:/var/lib/postgresql

  upgrade:
    image: tuomasairaksinen/serviceform:latest
    user: root
    env_file: env/staging.list
    command: upgrade
    links:
      - staging-db
      - staging-redis
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx-config:/nginx-config
      - celery-beat-store:/celery-beat-store

  celery:
    image: tuomasairaksinen/serviceform:latest
    command: celery
    env_file: env/staging.list
    links:
      - staging-redis
      - staging-db
    depends_on:
      - upgrade

  celery-beat:
    image: tuomasairaksinen/serviceform:latest
    command: celery-beat
    env_file: env/staging.list
    links:
      - staging-db
      - staging-redis
    volumes:
      - celery-beat-store:/store
    depends_on:
      - upgrade

  task-processor:
    image: tuomasairaksinen/serviceform:latest
    command: task-processor
    env_file: env/staging.list
    links:
      - staging-db
      - staging-redis
    depends_on:
      - upgrade

  send-emails:
    command: send-emails
    image: tuomasairaksinen/serviceform:latest
    env_file: env/staging.list
    links:
      - staging-db
    depends_on:
      - upgrade

  app:
    image: tuomasairaksinen/serviceform:latest
    env_file: env/staging.list
    command: app
    links:
      - staging-db
      - staging-redis
    volumes:
     - static:/code/static:ro
     - media:/code/media
    depends_on:
      - upgrade

  web:
    image: nginx:1.11
    env_file: env/staging.list
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - static:/serviceform-static:ro
      - media:/serviceform-media:ro
      - nginx-config:/etc/nginx/conf.d:ro